#!/bin/sh

if [ -e easymmo.doc ] then
cd ..
fi

## Install Erlang/OTP
sudo apt-get -y install build-essential libncurses5-dev libssl-dev
wget http://download.basho.co.jp.cs-ap-e2.ycloud.jp/otp/download/otp_src_18.0.tar.gz
tar xvf otp_src_18.0.tar.gz
cd otp_src_18.0
./configure -prefix=$HOME/otp_18.0
make
sudo make install
echo "PATH=$PATH:$HOME/otp_18.0/bin" >> $HOME/.profile
source $HOME/.profile

## Install RabbitMQ server
sudo apt-get -y install rabbitmq-server

## Install Riak
sudo echo "# this file was generated by packagecloud.io for" > /etc/apt/sources.list.d/basho.list
sudo echo "# the repository at https://packagecloud.io/basho/riak" >> /etc/apt/sources.list.d/basho.list
sudo echo "deb https://packagecloud.io/basho/riak/ubuntu/ precise main" >> /etc/apt/sources.list.d/basho.list
sudo echo "deb-src https://packagecloud.io/basho/riak/ubuntu/ precise main" >> /etc/apt/sources.list.d/basho.list
sudo apt-get update
sudo apt-get -y --force-yes install riak

## Install rebar
git clone https://github.com/basho/rebar.git
cd rebar
make
cp rebar ../easymmo
git clone https://github.com/rebar/rebar.git

## End of installation
echo "Please start riak."
echo "(you can reboot this system to start riak)."

