{application,easymmo,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{easymmo_app,[]}},
              {env,[]},
              {modules,[chat_srv,easymmo,easymmo_app,easymmo_sup,move_srv,
                        time_feeder]}]}.
